version: "3.8"

services:
  ubuntu24x86-service:
    container_name: Ubuntu24x86-Container
    image: ubuntu24x86
    volumes:
      - .:/mainDir/AI-ML-document-searching
    networks:
      - ubuntuNetwork
    ports:
      - "8000:8000"

  qdrant-service:
    container_name: Qdrant-Container
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - qdrant-storage:/qdrant/storage
    networks:
      - ubuntuNetwork

networks:
  ubuntuNetwork:

volumes:
  pip-cache:
  qdrant-storage:
